// Code generated by "stringer -type=DevState"; DO NOT EDIT.

package unifi

import "strconv"

const _DevState_name = "DisconnectedConnectedPendingDisconnectingUpgradingProvisioningHeartbeatMissingAdoptingDeletingManagedByOthersAdoptionFailedIsolatedIsolationPendingAdoptingWireless"

var _DevState_index = [...]uint8{0, 12, 21, 28, 41, 50, 62, 78, 86, 94, 109, 123, 131, 147, 163}

func (i DevState) String() string {
	if i < 0 || i >= DevState(len(_DevState_index)-1) {
		return "DevState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DevState_name[_DevState_index[i]:_DevState_index[i+1]]
}
