// Code generated by "stringer -type=STP"; DO NOT EDIT.

package unifi

import "strconv"

const (
	_STP_name_0 = "StpDisabledStpBlockingStpListeningStpLearningStpForwarding"
	_STP_name_1 = "StpUnknown"
)

var (
	_STP_index_0 = [...]uint8{0, 11, 22, 34, 45, 58}
)

func (i STP) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _STP_name_0[_STP_index_0[i]:_STP_index_0[i+1]]
	case i == 9:
		return _STP_name_1
	default:
		return "STP(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
